# Generated by Django 4.2.2 on 2023-06-07 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Movie",
        ),
    ]
